#!/bin/bash



# Makefile is hard to write and optimized for compilation

PI_SRC=pi/src

if [ -z $1 ]
then
	echo "Give server or client as argument"
	exit 1
fi

if [ $1 == 'client' ]
then
	echo "Building client"
	cp $PI_SRC/RunPi.sh ./
	chmod +x RunPi.sh
	exit 0
fi

if [ $1 == 'server' ]
then
	echo "Building server"

	# Pi sources
	cd pi/src/
	bash BuildBranchPi.sh
	cd ../..
	cp $PI_SRC/Controller.py ./
	cp $PI_SRC/RunServer.sh ./
	chmod +x RunServer.sh


	exit 0
fi


