#!/bin/bash



# Makefile is hard to write and optimized for compilation

PI_SRC=pi/src
INSTALL_DIR=./build
ROOT=$(pwd)


echo "Cleaning old installation (removing $INSTALL_DIR)"
rm -rf $INSTALL_DIR

if [ -z $1 ]
then
	echo "Give server or client as argument"
	exit 1
fi

if [ $1 == 'client' ]
then
	echo "Building client..."

	mkdir $INSTALL_DIR
	cp $PI_SRC/RunPi.sh $INSTALL_DIR/
	chmod +x $INSTALL_DIR/RunPi.sh



fi
if [ $1 == 'server' ]
then
	echo "Building server..."
	pip3 install enlighten --user

	mkdir $INSTALL_DIR

	cp $PI_SRC/Controller.py $INSTALL_DIR/Controller.py
	cp $PI_SRC/RunServer.sh $INSTALL_DIR/
	chmod +x $PI_SRC/RunServer.sh
	echo "Creating dataset..."
	cd cv/data
	bash CreateDataset.sh
	cd ../..



fi

printf "\t Creating symbolic links\n"
cd $INSTALL_DIR
ln -s ../pi
ln -s ../cv
cd $ROOT

echo "Changes are written to $INSTALL_DIR"
echo "Done!"

exit 0
