"""empty message

Revision ID: 649e51d95bc4
Revises: a587b1df38ab
Create Date: 2020-05-31 17:58:12.125137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649e51d95bc4'
down_revision = 'a587b1df38ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denial__time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denial__time_time'), 'denial__time', ['time'], unique=False)
    op.create_table('fed__time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fed__time_time'), 'fed__time', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fed__time_time'), table_name='fed__time')
    op.drop_table('fed__time')
    op.drop_index(op.f('ix_denial__time_time'), table_name='denial__time')
    op.drop_table('denial__time')
    # ### end Alembic commands ###
