"""last refill time

Revision ID: 931e5cc715bf
Revises: fb48a9c952c6
Create Date: 2020-05-17 14:33:51.459259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931e5cc715bf'
down_revision = 'fb48a9c952c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('last_refill_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_device_last_refill_time'), 'device', ['last_refill_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_last_refill_time'), table_name='device')
    op.drop_column('device', 'last_refill_time')
    # ### end Alembic commands ###
