"""empty message

Revision ID: a587b1df38ab
Revises: afa6591daee7
Create Date: 2020-05-29 01:13:38.372643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a587b1df38ab'
down_revision = 'afa6591daee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('turn_off', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('turn_on', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'turn_on')
    op.drop_column('device', 'turn_off')
    # ### end Alembic commands ###
