"""empty message

Revision ID: afa6591daee7
Revises: 931e5cc715bf
Create Date: 2020-05-28 10:58:08.644168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa6591daee7'
down_revision = '931e5cc715bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('is_on', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'is_on')
    # ### end Alembic commands ###
