"""charging status

Revision ID: fb48a9c952c6
Revises: 030155dfb703
Create Date: 2020-05-17 14:08:01.245386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb48a9c952c6'
down_revision = '030155dfb703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('is_charging', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'is_charging')
    # ### end Alembic commands ###
